runtime_config:
  env: flex # Use the flexible environment for more control
entrypoint: gunicorn -b :$PORT app:app # Keep your existing entrypoint
env_variables:
  NLTK_DATA: /Users/muhammadnazam/nltk_data # Set the NLTK_DATA path (adjust if needed)

runtime: python310

handlers:
  - url: /.*
    script: auto
